fix(ci): Install libxkbcommon-x11-0 on Linux
The AppImage creation tool now complains about a missing dependency:

ERROR: Could not find dependency: libxkbcommon-x11.so.0

So let's install it.